FROM node:18-alpine AS frontend-builder

WORKDIR /frontend
COPY frontend/package*.json ./
RUN npm install
COPY frontend/ ./
ARG REACT_APP_API_URL
ENV REACT_APP_API_URL=${REACT_APP_API_URL}
RUN npm run build

FROM node:18-alpine

WORKDIR /app
COPY backend-node/package*.json ./
RUN npm install --omit=dev
COPY backend-node/ ./
COPY dataset/ ./dataset/
COPY --from=frontend-builder /frontend/build ./public

EXPOSE 3000

CMD ["npm", "start"]
